[package]
name = "symphonia-format-riff"
description = "Pure Rust RIFF demuxer (a part of project Symphonia)."
authors = ["Philip Deljanov <philip.deljanov@gmail.com>", "dedobbin <dedobbindedobbin@gmail.com>"]
readme = "README.md"
categories = ["multimedia", "multimedia::audio", "multimedia::encoding"]
keywords = ["audio", "media", "demuxer", "aiff", "wav"]
# Common package metadata located in workspace Cargo.toml.
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["std", "aiff", "wav"]

# Enable standard-library I/O support. Disable for `no_std` (default-features = false).
std = ["symphonia-core/std", "symphonia-metadata/std"]

aiff = ["symphonia-metadata/riff-id3"]
wav = ["symphonia-metadata/riff-info"]

[dependencies]
extended = { version = "0.1.0", git = "https://github.com/NellowTCS/extended-rs/", rev = "b7e205ca" }
hashbrown = { version = "0.17", default-features = false, features = ["alloc", "default-hasher"] }
log = { workspace = true }

[dependencies.symphonia-core]
version = "0.6.1"
path = "../symphonia-core"
default-features = false

[dependencies.symphonia-metadata]
version = "0.6.1"
path = "../symphonia-metadata"
default-features = false
features = []

[lints]
workspace = true
