[package]
name = "symphonia-common"
description = "Project Symphonia utilities for codecs and formats."
authors = ["Philip Deljanov <philip.deljanov@gmail.com>"]
readme = "README.md"
categories = ["multimedia", "multimedia::audio", "multimedia::encoding"]
keywords = ["audio", "multimedia", "media", "xiph"]
# Common package metadata located in workspace Cargo.toml.
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["std"]

# Enable standard-library I/O support. Disable for `no_std` (default-features = false).
std = ["symphonia-core/std"]

[dependencies]
log = { workspace = true }

[dependencies.symphonia-core]
version = "0.6.1"
path = "../symphonia-core"
default-features = false

[lints]
workspace = true
