[package]
name = "symphonia-format-caf"
description = "Pure Rust CAF demuxer (a part of project Symphonia)."
authors = ["Ian Hobson <ian.r.hobson@gmail.com>", "Philip Deljanov <philip.deljanov@gmail.com>"]
readme = "README.md"
categories = ["multimedia", "multimedia::audio", "multimedia::encoding"]
keywords = ["audio", "media", "demuxer", "caf"]
# Common package metadata located in workspace Cargo.toml.
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["std"]

# Enable standard-library I/O support. Disable for `no_std` (default-features = false).
std = ["symphonia-core/std", "symphonia-common/std"]

[dependencies]
log = { workspace = true }

[dependencies.symphonia-common]
version = "0.6.1"
path = "../symphonia-common"
default-features = false

[dependencies.symphonia-core]
version = "0.6.1"
path = "../symphonia-core"
default-features = false

[lints]
workspace = true
